"""add file path to resumes

Revision ID: 6158bf856429
Revises: 003f6ccb6f35
Create Date: 2026-08-29 12:24:28.874456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6158bf856429'
down_revision: Union[str, Sequence[str], None] = '003f6ccb6f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column temporarily as nullable
    op.add_column(
        "resumes",
        sa.Column(
            "file_path",
            sa.String(length=500),
            nullable=True,
        )
    )

    # 2. Give existing resumes a temporary path
    op.execute(
        "UPDATE resumes "
        "SET file_path = 'legacy/unknown.pdf' "
        "WHERE file_path IS NULL"
    )

    # 3. Make the column required
    op.alter_column(
        "resumes",
        "file_path",
        existing_type=sa.String(length=500),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###
