"""rename password to password_hash

Revision ID: b42df5dd84a8
Revises: d1626ec1e3fc
Create Date: 2026-08-23 12:34:29.236781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42df5dd84a8'
down_revision: Union[str, Sequence[str], None] = 'd1626ec1e3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        new_column_name="password_hash"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        new_column_name="password"
    )
    # ### end Alembic commands ###
